import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.firstPageMain}>
        <div className={styles.firstPageFlex}>
          <h2 className={styles.appHeader}>That is To Do App </h2>
          <div className={styles.signBtnBlock}>
            <Link href='sign/in'>Sign In</Link>
            <Link href='sign/up'>Sign Up</Link>
          </div>
        </div>
      </main>
    </>
  )
}
